# Generated by Django 4.0.3 on 2022-03-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_options_project_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
    ]
