# Generated by Django 4.0.3 on 2022-04-04 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill_percent_ability_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.skill'),
        ),
    ]
